### ISSUE TITLE
Snes9x Compatibility List

### ISSUE THREAD

**Issue by Oggom** [snes9xgit/snes9x#53]
This has already been on the libretro wiki for quite some time, but I think it might be a good idea to post it here too:

A.S.P. Air Strike Patrol:
The shadow under the aircraft is missing.

Hayazashi Nidan Morita Shougi 2:
Matches won’t start.

Mecarobot Golf:
The ground “wobbles” during gameplay. Flickering graphics. 

Top Gear
Missing pixel garbage under the speed display. See https://github.com/snes9xgit/snes9x/issues/308

Fixed Issues:

Cho Aniki Bakuretsu Ranto-hen
~~Won't boot.~~ fixed as of https://github.com/snes9xgit/snes9x/commit/099bd60db0bec16b62a9351c32b24d3909ea55f2

Circuit USA
~~Broken graphics.~~ fixed as of https://github.com/snes9xgit/snes9x/commit/c22622806ded862eb5c9cbe9c040659ec80f1c69

Clayfighter 
~~The clownface turns blue when it should stay white..~~ fixed as of https://github.com/snes9xgit/snes9x/commit/1ca15b4a4f2cbbf3df64892eea41cdefc0a1ceb0

Daffy Duck: The Marvin Missions
~~Random screen flickering.~~ fixed as of https://github.com/snes9xgit/snes9x/pull/431/commits/2142282f69d7ee72d5ca851afe505536ff364ced

Dark Law
~~Garbage audio. Softlocks randomly.~~ fixed as of https://github.com/snes9xgit/snes9x/commit/fe6047213be802cb74cac724a1b83b7263c4dcca

Doom:
~~Colored dots appear during gameplay.~~ fixed as of https://github.com/snes9xgit/snes9x/commit/4345c20af2bcb15e3abfb3b3a796f2b3b6d991ba

Funaki Masakatsu Hybrid Wrestler – Tougi Denshou:
~~Corrupted graphics on the Pancrase logo screen.~~ fixed as of https://github.com/snes9xgit/snes9x/commit/9b595b5b197675f4b03a23794ec0d230224cf745

Joe and Mac 2
Often freezes when exiting a level on a dinosaur.
https://github.com/snes9xgit/snes9x/issues/660

JoJo no Kimyou na Bouken
~~Garbage characters show up during the intro~~ fixed as of https://github.com/snes9xgit/snes9x/commit/c96f6cd9138ad3c3f701b2e92c9864395e037677

Kat's Run - Zen-Nihon K-Car Senshuken
~~Graphical corruption during the gameplay demo.~~ fixed as of https://github.com/snes9xgit/snes9x/commit/d1b90ddb96995875b1248fc4dadc4a3f9288585d

Kick Off
~~Garbage graphics~~ fixed as of https://github.com/snes9xgit/snes9x/commit/c96f6cd9138ad3c3f701b2e92c9864395e037677

Light Fantasy
~~Game doesn't save properly.~~ fixed as of https://github.com/snes9xgit/snes9x/commit/e4d08bb71a3355bb4ba0a31885584754df2e1dab

M.A.C.S. Basic Rifle Marksmanship
~~Flickering graphics.~~ fixed as of https://github.com/snes9xgit/snes9x/commit/f139bf704fa7e36e2dd12f354bed8d9658cf100b

Marko's Magic Football
~~Crashes during the intro~~ fixed as of https://github.com/snes9xgit/snes9x/commit/756ef37d7feaf39ee4c163efe90677445d2cf3eb

Phalanx
~~Randomly freezes on the main menu.~~ fixed as of https://github.com/snes9xgit/snes9x/commit/d1b90ddb96995875b1248fc4dadc4a3f9288585d

PowerFest 94 - Super Mario Kart
~~Won't boot.~~ fixed as of https://github.com/snes9xgit/snes9x/commit/1c46c7ac565118f11788f3f4fddd26285d27aad9

Psycho Dream
~~Blank screen when starting a game..~~ fixed as of https://github.com/snes9xgit/snes9x/commit/e3216ec88e4d11c2fcbf37d46707caac3457bdd7

Secret of Evermore (PAL versions):
~~Randomly freezes when the background music changes.~~ fixed. See https://board.byuu.org/viewtopic.php?f=8&t=2065

Speedy Gonzales: Los Gatos Bandidos:
~~Freezes when pressing a switch in the last level.~~ fixed as of https://github.com/snes9xgit/snes9x/commit/355365046904b679d33b52c197ff423057ba6172

Stunt Race FX 
~~Garbage graphics on the course selection screen.~~ fixed as of https://github.com/snes9xgit/snes9x/commit/044113b0bfad670a3dd3db25638033b098b574b2

SuperFX
~~Transparency issues. See: https://github.com/snes9xgit/snes9x/issues/289~~ fixed as of https://github.com/snes9xgit/snes9x/commit/bd9db5726219392aa0b155642c6dcf7b6855ff55

Super Punch-Out!!
~~Crashes during the Mad Clown fight.~~ fixed as of https://github.com/snes9xgit/snes9x/commit/070d5e5dbf88b44eb46345aabc4247f994a941db

Super Pinball - Behind the Mask
~~Black screen after selecting a table. Heavy audio screeching.~~ fixed as of https://github.com/snes9xgit/snes9x/commit/fe6047213be802cb74cac724a1b83b7263c4dcca

**Comment by Oggom** [comment]
Updated the first post with some recent findings.

**Comment by vgturtle127** [comment]
You guys can start a Wiki on this GitHub if @snes9xgit approves. Or it could be documented in a text file in the repository, that would work as well. Doing it in an issue is probably not a good way to do it, however.

**Comment by Oggom** [comment]
Updated the first post due https://github.com/snes9xgit/snes9x/commit/fe6047213be802cb74cac724a1b83b7263c4dcca

Unfortunately this didn't fix the issue with the Secret of Evermore PAL release. Looks like the problem lies somewhere else here.

**Comment by jjfmz42015** [comment]
this should be on this list https://github.com/snes9xgit/snes9x/issues/250

**Comment by Oggom** [comment]
Finally found some time to update the list.

**Comment by jjfmz42015** [comment]
Phalanx
Randomly freezes on the main menu.

Not random. freezes trying to enter game play mode or attract mode. its very specific.

**Comment by Oggom** [comment]
> Not random. freezes trying to enter game play mode or attract mode. its very specific.

I've successfully been able to play the game several times with no softlocking whatsoever.  Freezes happen, but they are not consistent in any way for me.

If you can reproduce consistently you should reply to the corresponding issue https://github.com/snes9xgit/snes9x/issues/206 and explain how and when exactly it happens, what settings you use and what build of the emulator you're using.

**Comment by jjfmz42015** [comment]
Ok I found out why I thought its not random. If you boot Phalanx and fast forware till attract mode will always crash right away. however if you dont fast forward it wont always crash. so I guess its a timing issue.

**Comment by bearoso** [comment]
Fast forwarding, because you aren't providing any input, is deterministic, so the timing will be the same every time. Thanks for the hint. It'll be useful when I look into this.

**Comment by jjfmz42015** [comment]
I thought it was worth mentioning since the final outcome is always identical.
Its a pattern.

**Comment by jjfmz42015** [comment]
Just tested latest Phalanx is fixed!

**Comment by jjfmz42015** [comment]
super off road should be on this list due to difficulty being low due to lack of memory randomization

Uniracers should be on this list as well 2 player mode issue.

**Comment by jjfmz42015** [comment]
for A.S.P. Air Strike Patrol would it be as simple as getting permission from byuu to use his accurate ppu and have snes 9x auto switch to it for this one game?

**Comment by bearoso** [comment]
No. The PPU is very ingrained into Snes9x, so replacing it would be the equivalent of replacing the whole emulator. It would be easier to make the current one render dot-by-dot.

**Comment by jjfmz42015** [comment]
Would it be possible to make it render dot by dot just for that game and as is for the rest?

**Comment by jjfmz42015** [comment]
looking at this list i wouldnt call top gear "an issue" the "issue" is more like an enhancement.

**Comment by jjfmz42015** [comment]
Stunt Race FX bug is not present in zsnes. dont know if knowing this might help in any way? If memory serves people that contributed to sfx on znes also did so on snes9x maybe they can compare code? i dunno?

**Comment by Tatsuya79** [comment]
Stunt Race FX
Garbage graphics on the course selection screen

fixed with https://github.com/snes9xgit/snes9x/commit/044113b0bfad670a3dd3db25638033b098b574b2

**Comment by Oggom** [comment]
Updated, thanks! I've also added Clayfighter and Psycho Dream to the solved issue list.

**Comment by Tatsuya79** [comment]
I noticed the ground stop wobbling in Mecarobot Golf with even a light overclock.

**Comment by jjfmz42015** [comment]
Slight over clock of what?

**Comment by Tatsuya79** [comment]
The cycle hack, "Reduce Slowdown" in retroarch.

**Comment by jjfmz42015** [comment]
Oh didn't know that function is there using windows version here. That is the only feature I miss from Zsnes for rtype I would set percent to execute to 150% to eliminate slowdowns during game play. I wish they add this to GUI in win version

**Comment by retrotalker** [comment]
https://github.com/snes9xgit/snes9x/commit/f139bf704fa7e36e2dd12f354bed8d9658cf100b

should cure M.A.C.S. simulator.

**Comment by Tatsuya79** [comment]
Mecarobot Golf:
The ground “wobbles” during gameplay. Flickering graphics.

Fixed with https://github.com/snes9xgit/snes9x/commit/c61d81269a16ba045bddcc98716b4391ac317184

**Comment by bearoso** [comment]
> Mecarobot Golf:
The ground “wobbles” during gameplay. Flickering graphics.

Fixed with c61d812

It's better, but not fixed yet.

**Comment by Tatsuya79** [comment]
Really? I hardly see any difference with Higan now.
I mean it wobbles a bit during a shot animation with both emus (perhaps more on snes9x? can't say for sure).

**Comment by bearoso** [comment]
It flickers a bit, too. 
Trust me, it's not quite fixed. We need to allow the extra opcode to execute, but we'll have to find out why that hurts the dragon ball game.

**Comment by lacastri** [comment]
If you mean DBZ: Super Butouden 2 split-screen flicker, I checked bsnes and opcode cycles match snes9x svn. Only deviations I saw is that at 00:ffab irq handler
- snes9x svn runs at 28.638 -- 28.676
- bsnes runs at 28.640 -- 28.668


Both avoid hdma 2114 scroll glitch. And the usual time when hdma transfer shows up in the logs:
```
808344 ldx $092e     [80092e] A:b901 X:000c Y:000c S:1fdf D:0000 DB:80 nvMxdIzC V: 28 H:1084 F:14
808347 lda $0945     [800945] A:b901 X:cc33 Y:000c S:1fdf D:0000 DB:80 NvMxdIzC V: 28 H:1118 F:14
** hdma
80834a and #$02               A:b97e X:cc33 Y:000c S:1fdf D:0000 DB:80 nvMxdIzC V: 28 H:1276 F:14


$80:8341 8D 14 21    STA $2114  [$80:2114]   A:8001 X:001C Y:001E D:0000 DB:80 S:1FE0 P:envMxdIzC HC:1060 VC:028 FC:09  HV .n.    HT:558 VT:28 C:357926
$80:8344 AE 2E 09    LDX $092E  [$80:092E]   A:8001 X:001C Y:001E D:0000 DB:80 S:1FE0 P:envMxdIzC HC:1084 VC:028 FC:09  HV .n.    HT:558 VT:28 C:357926
--- HC event processing  (HC_HBLANK_START_EVENT)  expected HC:1096  executed HC:1102 VC:0028
--- HC event rescheduled (HC_HDMA_START_EVENT  )  expected HC:1106  current  HC:1102
--- HC event processing  (HC_HDMA_START_EVENT  )  expected HC:1106  executed HC:1118 VC:0028
*** HDMA Transfer HC:1118, Channel:6a
```


Still trying to grab another log of Golf wobble or flicker.

**Comment by Panderner** [comment]
Hayazashi Nidan Morita Shogi 2 requires ST018 which is not implemented on snes9x but bsnes can

**Comment by Eggo-dotcom** [comment]
add joe & mac 2 as not compatible.

https://github.com/snes9xgit/snes9x/issues/660
